import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { ReactNode } from 'react';
import { Header } from '@/layout/Header/Header';
import { Footer } from '@/layout/Footer/Footer';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Providers } from '@/providers/Providers';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/effect-cards';
import '@/assets/styles/index.scss';

const montserrat = Montserrat({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <GoogleAnalytics gaId='G-4PTRVLFR5Z'/>
      <body className={montserrat.className}>
        <Providers>
          <div className='container'>
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
